version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    environment:
      SERVICE_LABEL: vn_student_progress_report
    expose:
      - '4200'
    ports:
      - '4200:4200'
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DB=spr_api
      - MYSQL_PASSWORD=kidsloop
    ports:
      - 3306:3306
